--
-- PostgreSQL database dump
--

\restrict k4mCDOpQvnyst9ThENgcHhD2zJOhKbIm6Sxi5Pl43A4OMHI9flQPfSohUrk7tJl

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-24 13:23:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 229 (class 1259 OID 17132)
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    device_id character varying(255)
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17152)
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17151)
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17161)
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17160)
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 17266)
-- Name: attendance_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_log (
    id uuid NOT NULL,
    date date NOT NULL,
    clock_in timestamp with time zone,
    clock_out timestamp with time zone,
    source character varying(50) NOT NULL,
    latitude double precision,
    longitude double precision,
    photo_evidence character varying(100),
    is_late boolean NOT NULL,
    is_overtime boolean NOT NULL,
    overtime_duration interval,
    kpi_score integer,
    employee_id uuid NOT NULL
);


ALTER TABLE public.attendance_log OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17086)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17085)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17096)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17095)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 17076)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17075)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 17311)
-- Name: daily_report_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.daily_report_log (
    id bigint NOT NULL,
    date date NOT NULL,
    activity text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    employee_id uuid NOT NULL,
    issue text,
    work_link character varying(500)
);


ALTER TABLE public.daily_report_log OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17310)
-- Name: daily_report_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.daily_report_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_report_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17199)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17198)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17064)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17063)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17052)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17051)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17253)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17225)
-- Name: employees_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees_employee (
    id uuid NOT NULL,
    nik character varying(50) NOT NULL,
    full_name character varying(255) NOT NULL,
    nickname character varying(100),
    hikvision_id character varying(50),
    whatsapp_number character varying(255) NOT NULL,
    emergency_contact character varying(255),
    gender character varying(20) NOT NULL,
    religion character varying(50),
    address text,
    role character varying(100) NOT NULL,
    birth_place character varying(100),
    birth_date date,
    join_date date NOT NULL,
    bank_account_info character varying(255),
    is_active boolean NOT NULL,
    user_id uuid,
    contract_end_date date,
    contract_type character varying(50) NOT NULL
);


ALTER TABLE public.employees_employee OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17283)
-- Name: leave_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_request (
    id uuid NOT NULL,
    leave_type character varying(20) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text NOT NULL,
    attachment character varying(100),
    status character varying(20) NOT NULL,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    approved_by_id uuid,
    employee_id uuid NOT NULL,
    signed_attachment character varying(100)
);


ALTER TABLE public.leave_request OWNER TO postgres;

--
-- TOC entry 5155 (class 0 OID 17132)
-- Dependencies: 229
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, id, device_id) FROM stdin;
pbkdf2_sha256$1500000$MNDRjkTC1MplAE2Y58jme1$KsfF6ti9VSZJ2lbK12jpUH9jvDUgSt/QlacR8V6RtnM=	\N	t	admin			admin@omahvisual.com	t	t	2026-09-21 14:27:19.872754+07	d7461acb-897c-4cf3-a40c-d3cc40c7b64d	\N
pbkdf2_sha256$1500000$My10ehfDyRPrXYhfeQG25C$j4GQCtdRQIsf2sB7t2Duu0dOf1beIDpZw7c7iwlniHU=	\N	f	6				f	t	2026-09-21 14:27:32.688581+07	a29d9a03-f8d7-4834-b960-69e89c4b5374	\N
pbkdf2_sha256$1500000$ZB6kCoTwKifjfn6gCD8aaK$Adiov9xYIGulfdlRklIvRUqjGmXSOCwKtfelR6bKa4s=	\N	f	7				f	t	2026-09-21 14:27:33.248764+07	169a4b70-c6bf-4d32-9073-cc77b1d04b38	\N
pbkdf2_sha256$1500000$uxW2scsEm3eVkB8Jazss0E$S/85X6J7ZgwuLMDZRS/Fdg8HC6C6xsdU2wzIH1g/oj8=	\N	f	8				f	t	2026-09-21 14:27:33.779208+07	0699aedd-4d97-46fa-a4b0-1298728e1a92	\N
pbkdf2_sha256$1500000$XTInsKkqpk5tNu8dbayXoj$r3paSLwMQ0fwuufnlIVtfxDiQSdhJJ4GoqDTQpgC7B4=	\N	f	9				f	t	2026-09-21 14:27:34.287119+07	10c4ff7f-50fe-4df2-b0ab-c692ad70650f	\N
pbkdf2_sha256$1500000$h30LRv2Wm2qILNPkGTBInr$S837mhUb2vcr7XFVtPUh3SZiyXpUb9ZTHb7jJoB7xMk=	\N	f	10				f	t	2026-09-21 14:27:34.788903+07	8e77bc52-17b2-4448-ac0c-a7d0cf8e1e7b	\N
pbkdf2_sha256$1500000$FMN6HHg0sCOBOQi5HAOFfK$PppXC2OrNENuTmGtXYeyTyoIXsydfJzN58dfFvTMmkQ=	\N	f	11				f	t	2026-09-21 14:27:35.321809+07	5e447a5b-0654-45e5-93bf-f48368302cfb	\N
pbkdf2_sha256$1500000$w172iVmmAKeJssPW2DLzdN$+sVyESBiPM4akbvbqVLlGs9nZcXcYD/J98lSDpo6BhQ=	\N	f	12				f	t	2026-09-21 14:27:35.865549+07	d1b82217-662e-442f-9778-1c98753f4bf8	\N
pbkdf2_sha256$1500000$SZCbFoUk75NbHGicfXg7QN$dEN0eAomTsfUOTW3kLE3TWXJop6S9ULtyVbgVvSlOKE=	\N	f	13				f	t	2026-09-21 14:27:36.390546+07	1ab278c1-1c7d-43d3-aabe-a559e203ca7e	\N
pbkdf2_sha256$1500000$IF7y52YOreILU4xq8LQV3P$F1xvmGdXgephhNoPbKA0mFf+4kndE/DNO3DRFq4E/Xc=	\N	f	14				f	t	2026-09-21 14:27:36.895607+07	9155ac98-245e-464d-89c2-9e80b40f6e97	\N
pbkdf2_sha256$1500000$XPnPwIeTTTRDV9Gji4tvgx$GCueH/VG7cGUIfFiZjMpizUF85fxwCHdRfo6pW5BleQ=	\N	f	15				f	t	2026-09-21 14:27:37.431411+07	26598084-ba7b-4821-ac9c-e7f9a95e471d	\N
pbkdf2_sha256$1500000$RFpeWP9cASthY2QvIQk2EJ$ytdlIQfEfgXrtwfWozMHvhf4fm6mx6Pd6UE+XZo+Yuk=	\N	f	16				f	t	2026-09-21 14:27:37.935729+07	44ea45de-92ae-4502-be48-5633ffe138d7	\N
pbkdf2_sha256$1500000$zXM38JbjHCcLCfxz2GWfCI$FUorybRe80MC0R/0DLsuepueGXSfj0VlVeL2kWDDAjY=	\N	f	17				f	t	2026-09-21 14:27:38.446233+07	53bc4d2a-f69f-4dad-823a-8062b0ee84b1	\N
pbkdf2_sha256$1500000$Ky9KJqfzB8YYFMXFi4TeaZ$t6MKAkJziGjSoQabBinlkAHLmAAW/2Nm7RlnaI+WJYI=	\N	f	18				f	t	2026-09-21 14:27:38.971046+07	9341323e-75fc-43ff-8138-36c623964bd7	\N
pbkdf2_sha256$1500000$In27iwrquFhELVXZrolt5B$GaLEMaz0zyrOBUbe0I1lQqjYYDITCxjowUWDqrSZX4c=	\N	f	19				f	t	2026-09-21 14:27:39.499515+07	a2435db0-5e2f-452e-a055-952ed801a6a1	\N
pbkdf2_sha256$1500000$3NSPlOoWZSMqCmwf7VS5RA$THXaKGHZxOrXWnxMiThiK9gvOjEf4Bbs+7JAGSJqsao=	\N	f	20				f	t	2026-09-21 14:27:40.023328+07	3bc45f4e-7afd-4b10-a26d-47ac3dfbc12c	\N
pbkdf2_sha256$1500000$K0jxXMg1ttO0wMyS4DqNKT$E/ojraMhqvBIHJuHBJUBifheNGnVdvVurrAMMHti7rc=	\N	f	21				f	t	2026-09-21 14:27:40.5319+07	f497a7ab-b821-4d1d-bb81-7bda28c651be	\N
pbkdf2_sha256$1500000$lwKdGBXqx14pXTN3whj41v$6ax5qj1065+k976NAmjPWJ0CZy7tI3jWagcaqsMPA4Q=	\N	f	22				f	t	2026-09-21 14:27:41.042867+07	7a02ad93-1a6b-4349-97d8-2c9e5c4a0972	\N
pbkdf2_sha256$1500000$Q4z8Q3MJ8xbdBKMV8XFysy$6pMcc1/HjbPCNI6Nu2Bzg4Cly80qErIGHFw9eL0D3Fo=	\N	f	23				f	t	2026-09-21 14:27:41.562287+07	799aed62-f698-4ca5-9f2e-4c393275cc26	\N
pbkdf2_sha256$1500000$iu6ngE58M9W8ooWhvjup1y$XXI5xLl2EzRWRMukzWch6o1KnV4ysBA3YPnuuTIx3OE=	\N	f	24				f	t	2026-09-21 14:27:42.103396+07	98231609-79ae-44f6-a19f-617801443438	\N
pbkdf2_sha256$1500000$72PkBjBth0oZb8Cf2pTugf$DtMHC01HHKU1ABqbU5QgeYixzgDKAFa+kVSGLPks+q8=	\N	f	25				f	t	2026-09-21 14:27:42.649905+07	85fe04f3-309c-4502-8032-1ba9d54abb2c	\N
pbkdf2_sha256$1500000$AUT5c38J7SBWPhROcmLcr2$ZcvvvNAFNTETI0LfgmmjJ+sEJwtTs/SkDoQZTfLYdss=	\N	f	26				f	t	2026-09-21 14:27:43.189183+07	7864f3ac-dc94-416c-8609-e00dfec23a25	\N
pbkdf2_sha256$1500000$BmreSGoQC33xV4cxzIE32E$HWMjJA/j7DzXkzyDkG/HXpsQXL3eZDkawlP5ef9IWr4=	\N	f	27				f	t	2026-09-21 14:27:43.770189+07	e7f3f43c-8560-42c9-9817-1b8967734a53	\N
pbkdf2_sha256$1500000$j6YblNhRrqPTHrTIvzCRbQ$c7CDIf1+MVFGQAbUX/3Bly5bUmML9AvSXUucwS0v54Q=	\N	f	28				f	t	2026-09-21 14:27:44.301922+07	dc75610d-dd54-494b-8011-1c702593afac	\N
pbkdf2_sha256$1500000$VIM1vJlpIxL2Nxm4awL79m$WyJBxfX+xVv1+RGvmxCtyLqxVIGFnAddBJ2kJtbJ3h8=	\N	f	29				f	t	2026-09-21 14:27:44.826845+07	247acbcc-3d48-47b6-877d-d37f44ebf8cb	\N
pbkdf2_sha256$1500000$sjqkhAlMEXwpoViVByGnIw$Z7wf/XfIMxU/y0amjKwvMVrjgiMuobpzDo6oXRpsoG4=	\N	f	30				f	t	2026-09-21 14:27:45.355436+07	44886b3f-678e-48cc-a3af-dfe9827ee5a2	\N
pbkdf2_sha256$1500000$mwSXYD51vjAJGTSWNNjz1F$JblPXTr/+0cZsSguWQZLn0uHYgUjdJnc00lDbIgwYZA=	\N	f	31				f	t	2026-09-21 14:27:45.872094+07	1d4f2713-0e41-4ac0-b47a-bf41132c9a2b	\N
pbkdf2_sha256$1500000$5WjNW6HASVH0KGpqmxcf8Y$5X2Qr7bnmW82/rphFC1dArG6HKyCtIZS6j9CCvuv/W8=	\N	f	32				f	t	2026-09-21 14:27:46.38989+07	745c6581-f30f-4e04-b65d-0fa1a508d2b1	\N
pbkdf2_sha256$1500000$dZScYGKHH6UPtBXYx9c5Ab$tm1QmXgG221w0K7p5rMtNCmg5lK/7u0ImFNaeDCLp3E=	\N	f	34				f	t	2026-09-21 14:27:46.906147+07	694d2fe2-591c-4ae0-8bed-8b7761ddb8d8	\N
pbkdf2_sha256$1500000$1YUNr2aSIEj8FJPgFYh6bI$UtayLgwDstKujTKGUb1herDIluBBCeF/n62ujQEUlng=	\N	f	36				f	t	2026-09-21 14:27:47.446018+07	004649fc-e4c1-41f9-a5e2-73554219984b	\N
pbkdf2_sha256$1500000$hNwtiMsq8HaxpqxHrxxA41$d0k6pmQkrAjzcaHlem4v/gnKuCGJEgKa30vq4yaBmdc=	\N	f	37				f	t	2026-09-21 14:27:47.978955+07	53a13204-e5cd-4346-b6b3-1a72a7b6d2b7	\N
pbkdf2_sha256$1500000$rolOazXuFBzTItgjgaKRRj$PmRSYiqEpRg8ZkDDcHBMcv9b8bF6EW2F0Rq6t1WhT8Y=	\N	f	38				f	t	2026-09-21 14:27:48.542706+07	f2099cc8-37da-488e-b8a6-e79bb8e12ac1	\N
pbkdf2_sha256$1500000$sl8aBEMRdjjXUOb9VYC5dh$fZ5sM1gJMvQsWssqjjtHNoOONZSNznMNpMeWx4GrTQE=	\N	f	1				f	t	2026-09-21 14:27:49.101451+07	14d4cad5-189e-4b06-b121-72c148cc0751	\N
pbkdf2_sha256$1500000$ZW98wakxvQ3H2mjsLDgbAT$xBlvUQr+oJsAo1KLVkjZ4d6DDdvQDdjDnBBLb64mQSk=	\N	f	3				f	t	2026-09-21 14:27:49.66438+07	02c94227-b66b-4ecb-a643-0c0a21c8bd6c	\N
pbkdf2_sha256$1500000$XR4rwcBqKEubKxaJrKc7yT$AXztZkMvGkd6r0L2/PwuwTVhjyR843gUHfiqgJLIfB0=	\N	f	5				f	t	2026-09-21 14:27:50.189442+07	7e583f6c-1c82-4425-b357-a9cd22d4ef00	\N
pbkdf2_sha256$1500000$TEaSRJcf8TDnCbVDAuMlBp$+9eglLWTsQIOI06uFFcnTXgElZryW88YAODEJjTItNI=	\N	f	35				f	t	2026-09-21 14:27:50.733677+07	aed9f0cc-755c-4a69-9e65-328f842a2ec7	\N
pbkdf2_sha256$1500000$jHdBDJwMkQ2Imb8ALYbSDD$8aIhS2HIr/3cWjnufZ9YltrvFYPJJ34qpEJ6iEmUWXk=	\N	f	2				f	t	2026-09-21 14:27:51.279117+07	f0ce7c83-d36a-404c-b193-76067e36d11d	\N
pbkdf2_sha256$1500000$Ktx7pkNfI6uCo3do4qh86R$MtZUzBukFJvhzVap7SM025v9QtwToSf8kjaieuo9IRU=	\N	f	4				f	t	2026-09-21 14:27:51.793734+07	8dca6df1-c978-4542-851a-a154d80d37a4	\N
pbkdf2_sha256$1500000$HCDrzHCllPxqZ33S9NHraF$zPkgr+0wYaxT8c3O4k9TzRyws7p6SOk+II1ym/eldKY=	\N	f	33				f	t	2026-09-21 14:27:52.387464+07	4ee8d821-bfd1-44dd-a03f-c4d2fb1cf433	\N
\.


--
-- TOC entry 5157 (class 0 OID 17152)
-- Dependencies: 231
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5159 (class 0 OID 17161)
-- Dependencies: 233
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5164 (class 0 OID 17266)
-- Dependencies: 238
-- Data for Name: attendance_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attendance_log (id, date, clock_in, clock_out, source, latitude, longitude, photo_evidence, is_late, is_overtime, overtime_duration, kpi_score, employee_id) FROM stdin;
eedf660a-d474-41a7-9f50-3832cdb2f2f1	2026-09-21	2026-09-21 16:15:00+07	\N	HIKVISION_MACHINE	\N	\N		f	f	\N	50	1b5de890-3254-4b8d-80f4-ab561b4bb2b1
806e8091-6315-4389-a509-7bc09744c570	2026-09-21	2026-09-21 14:55:00+07	2026-09-22 00:05:00+07	HIKVISION_MACHINE	\N	\N		f	f	\N	100	1d94258b-f050-4240-92de-74e22cb81194
34e5052b-5786-4fc3-9bc8-32037316e350	2026-09-21	2026-09-21 16:30:00+07	\N	HIKVISION_MACHINE	\N	\N		f	f	\N	50	d58b348b-992d-42e5-a1ad-c80887eaddcf
\.


--
-- TOC entry 5152 (class 0 OID 17086)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5154 (class 0 OID 17096)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5150 (class 0 OID 17076)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add employee	7	add_employee
26	Can change employee	7	change_employee
27	Can delete employee	7	delete_employee
28	Can view employee	7	view_employee
29	Can add attendance log	8	add_attendancelog
30	Can change attendance log	8	change_attendancelog
31	Can delete attendance log	8	delete_attendancelog
32	Can view attendance log	8	view_attendancelog
33	Can add leave request	9	add_leaverequest
34	Can change leave request	9	change_leaverequest
35	Can delete leave request	9	delete_leaverequest
36	Can view leave request	9	view_leaverequest
37	Can add daily log	10	add_dailylog
38	Can change daily log	10	change_dailylog
39	Can delete daily log	10	delete_dailylog
40	Can view daily log	10	view_dailylog
\.


--
-- TOC entry 5167 (class 0 OID 17311)
-- Dependencies: 241
-- Data for Name: daily_report_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.daily_report_log (id, date, activity, created_at, employee_id, issue, work_link) FROM stdin;
1	2026-09-22	jambreat	2026-09-22 11:42:03.377098+07	d58b348b-992d-42e5-a1ad-c80887eaddcf	\N	\N
2	2026-09-22	wdada	2026-09-22 11:55:59.630389+07	d58b348b-992d-42e5-a1ad-c80887eaddcf	adwada	https://github.com/hazehans/hris-omahvisual.git
3	2026-09-22	cek3	2026-09-22 13:31:04.931811+07	d58b348b-992d-42e5-a1ad-c80887eaddcf	daskda	https://github.com/hazehans/hris-omahvisual
4	2026-09-22	d3qwdadaw	2026-09-22 14:21:48.184029+07	d58b348b-992d-42e5-a1ad-c80887eaddcf		
5	2026-09-22	dwadwadadaadada	2026-09-22 14:22:02.241143+07	d58b348b-992d-42e5-a1ad-c80887eaddcf		
\.


--
-- TOC entry 5161 (class 0 OID 17199)
-- Dependencies: 235
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5148 (class 0 OID 17064)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	employees	employee
8	attendance	attendancelog
9	leave	leaverequest
10	daily_report	dailylog
\.


--
-- TOC entry 5146 (class 0 OID 17052)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-21 10:18:46.388521+07
2	contenttypes	0002_remove_content_type_name	2026-09-21 10:18:46.396136+07
3	auth	0001_initial	2026-09-21 10:18:46.415495+07
4	auth	0002_alter_permission_name_max_length	2026-09-21 10:18:46.418188+07
5	auth	0003_alter_user_email_max_length	2026-09-21 10:18:46.42046+07
6	auth	0004_alter_user_username_opts	2026-09-21 10:18:46.423579+07
7	auth	0005_alter_user_last_login_null	2026-09-21 10:18:46.428697+07
8	auth	0006_require_contenttypes_0002	2026-09-21 10:18:46.429869+07
9	auth	0007_alter_validators_add_error_messages	2026-09-21 10:18:46.432072+07
10	auth	0008_alter_user_username_max_length	2026-09-21 10:18:46.43459+07
11	auth	0009_alter_user_last_name_max_length	2026-09-21 10:18:46.437026+07
12	auth	0010_alter_group_name_max_length	2026-09-21 10:18:46.442168+07
13	auth	0011_update_proxy_permissions	2026-09-21 10:18:46.444656+07
14	auth	0012_alter_user_first_name_max_length	2026-09-21 10:18:46.447562+07
15	accounts	0001_initial	2026-09-21 10:18:46.473483+07
16	admin	0001_initial	2026-09-21 10:18:46.487062+07
17	admin	0002_logentry_remove_auto_add	2026-09-21 10:18:46.491001+07
18	admin	0003_logentry_add_action_flag_choices	2026-09-21 10:18:46.494356+07
19	employees	0001_initial	2026-09-21 10:18:46.506019+07
20	sessions	0001_initial	2026-09-21 10:18:46.510138+07
21	employees	0002_alter_employee_emergency_contact_and_more	2026-09-21 10:27:04.603672+07
22	attendance	0001_initial	2026-09-21 13:30:34.397508+07
23	leave	0001_initial	2026-09-21 13:30:34.412205+07
24	leave	0002_leaverequest_signed_attachment	2026-09-22 09:00:50.784363+07
25	daily_report	0001_initial	2026-09-22 11:34:13.921677+07
26	daily_report	0002_alter_dailylog_options_remove_dailylog_end_time_and_more	2026-09-22 11:38:33.849352+07
27	daily_report	0003_dailylog_issue_dailylog_work_link	2026-09-22 11:52:28.737536+07
28	daily_report	0004_alter_dailylog_date	2026-09-22 13:39:06.99067+07
29	employees	0003_employee_contract_end_date_employee_contract_type	2026-09-22 14:30:31.254704+07
\.


--
-- TOC entry 5163 (class 0 OID 17253)
-- Dependencies: 237
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5162 (class 0 OID 17225)
-- Dependencies: 236
-- Data for Name: employees_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees_employee (id, nik, full_name, nickname, hikvision_id, whatsapp_number, emergency_contact, gender, religion, address, role, birth_place, birth_date, join_date, bank_account_info, is_active, user_id, contract_end_date, contract_type) FROM stdin;
a68615a3-424f-492e-b1c2-36f605dc7b0e	6	Satrio Ilyas Putra Ashari	Rio	6	8561544610	81252474637	LAKI_LAKI	ISLAM	Jl bareng Tengah V-D / 767 Malang	Editor	Malang	2005-09-20	2024-01-02	BCA 3850873312 A.n Satrio Ilyas Putra Ashari	t	a29d9a03-f8d7-4834-b960-69e89c4b5374	\N	PKWT
86d0c1a8-66fd-4d5e-ae6f-e883a0a953e9	7	Allaam Rosyad Akbar	Allam	7	82296626160	81217265901	LAKI_LAKI	ISLAM	Jalan Wiroto II No. 07 02/07, Polehan, Blimbing, Kota Malang	Editor	Malang	2002-02-19	2025-04-01	BCA 4391154141 a.n Allaam Rosyad Akbar	t	169a4b70-c6bf-4d32-9073-cc77b1d04b38	\N	PKWT
f753b5b9-6db5-4bbe-8afe-e44be9a867ca	8	Ridho Yudagani Pratama	Ridho	8	81236663651	85755677289	LAKI_LAKI	ISLAM	Dusun 6 Panca Tunggal Sungai Lilin	Gudang Inventory	Badung	2004-08-08	2024-07-23	SEA BANK 901916669468 A/n Ridho Yudagani Pratama	t	0699aedd-4d97-46fa-a4b0-1298728e1a92	\N	PKWT
671d0cdf-3c8c-4153-aa86-c6b09a8b21b6	9	Aulia Diva Salsabillah	Diva	9	83185668010	83129150817	PEREMPUAN	ISLAM	Jl Blambangan Krebet Bululawang Kab.Malang	Customer Service	Malang	2006-02-24	2024-12-18	DANA 3901083185668010 a.n Aulia Diva	t	10c4ff7f-50fe-4df2-b0ab-c692ad70650f	\N	PKWT
d4607ba5-3b9d-4b52-b48c-143dc745147b	10	Annisa Faza Dea Maharani	Dea	10	85925141590	81554809822	PEREMPUAN	ISLAM	Jl Candi III 2A / 375  Malang	Finance	Malang	2003-04-10	2025-01-21	BCA 0113013548 Annisa Faza Dea Maharani	t	8e77bc52-17b2-4448-ac0c-a7d0cf8e1e7b	\N	PKWT
c3a7d21d-0925-41da-8916-003d01bbd556	11	Yusril Panggabean	Yusril	11	82338501553	82335357914	LAKI_LAKI	ISLAM	Perumahan turen permai B03 Rt 001 Rw 010\nDesa Talangsuko, Kab. Malang	Parttime Rental	Malang	2007-01-29	2025-05-01	BCA 6295056898 a.n Yusril Panggabean	t	5e447a5b-0654-45e5-93bf-f48368302cfb	\N	PKWT
fae18878-2c86-4652-94c3-4ed146d37a89	12	Pandu Fajri Pambudi	Pandu	12	85733301587	81334585892	LAKI_LAKI	ISLAM	Jalan Candi Jago No. 06 02/10, Blimbing, Kota Malang	Parttime Rental	Malang	2005-01-22	2025-05-01	BCA 8161641952 a.n Pandu Fajri Pambudi	t	d1b82217-662e-442f-9778-1c98753f4bf8	\N	PKWT
8e968c6b-88eb-4a2a-bc25-1f34af6c1121	13	Ronald Fathur Abyantara	Byan	13	82245676551	8125256313	LAKI_LAKI	ISLAM	Jalan Rogonoto Timur Rel KA 03/01, Singosari, Kab. Malang	Gudang Inventory	Malang	2006-07-31	2025-06-15		t	1ab278c1-1c7d-43d3-aabe-a559e203ca7e	\N	PKWT
f27d441c-ff51-4569-b74a-d9f644f9790f	14	Andika Rendy Ferdiansyah	Andhika	14	88989606130	881027848337	LAKI_LAKI	ISLAM	Dsn Glatik toyomarto Singosari Kab malang	Editor	Malang	2006-02-18	2025-01-02	-	t	9155ac98-245e-464d-89c2-9e80b40f6e97	\N	PKWT
f65d8804-c377-4ecf-b503-46b18698bb92	15	Bobyvio Mirza Lavfidi	Boby	15	85954314751		LAKI_LAKI	ISLAM	Jl Raya Sawojajar No 1 Malang	Pic Led	Malang	2000-02-08	2023-09-01	BCA 3310521310 A/n Muhammad Iqbaluzzaman	t	26598084-ba7b-4821-ac9c-e7f9a95e471d	\N	PKWT
cbe0544c-04a2-40e2-81ad-30a8a3821f82	16	Caesario Priatama Panjalu	Rio	16	87775995932		LAKI_LAKI	ISLAM	Jl. soponyono Gg mandiri Rt 4 Rw 2, Kelurahan Losari, singosari, Malang	Crew Led	Malang	2004-08-07	2024-10-04	3680504058 BCA A/n Caesario P,P	t	44ea45de-92ae-4502-be48-5633ffe138d7	\N	PKWT
b243b859-2518-498b-bbbf-5304920bcabd	17	Yoga Taufani Mahfud	Yoga	17	8815585525		LAKI_LAKI	ISLAM	Jl Raya Panggungrejo Rt 01 Rw 03 Malang	Pic Led	Malang	1998-07-01	2023-08-15	BCA 8160835851 A/n Yoga Taufani	t	53bc4d2a-f69f-4dad-823a-8062b0ee84b1	\N	PKWT
0274c8e8-ede4-42cb-b35b-4bed30e8e0db	18	Mochammad Bagus Sasongko	Bagus	18	88991115724		LAKI_LAKI	ISLAM	Trucuk 04/01, Kab. Bojonegoro		Bojonegoro	2003-08-27	2026-09-21		t	9341323e-75fc-43ff-8138-36c623964bd7	\N	PKWT
c3558401-7c3e-497b-bce0-082721b7ed7e	19	Apip Syihabuddin Rohim	Apip	19	82335040432		LAKI_LAKI	ISLAM	Gubuk Timur, Poh Gading, Lombok Timur, NTB		Mojokerto	2002-12-09	2026-09-21		t	a2435db0-5e2f-452e-a055-952ed801a6a1	\N	PKWT
28dc8c13-10b8-45bc-bdaa-dfd674060885	20	Nazriel Bagus Anandra	Andra	20	85855858317		LAKI_LAKI	ISLAM	Perum Sukun Pondok Indah Blok Y - 26, Bandungrejosari, Sukun		Malang	2005-07-29	2026-09-21		t	3bc45f4e-7afd-4b10-a26d-47ac3dfbc12c	\N	PKWT
e4b31150-22f9-4381-8e2b-406822cc8f04	21	Faishal Yahya Hariyadi	Acil	21	85646727036		LAKI_LAKI	ISLAM	Jl Indroprastono No 8 Rt02 Rw 03 Malang	Staff Sarana Prasarana	Malang	2002-05-09	2023-12-01	BCA 113114981 A/n Faishal Yahya Hariadi	t	f497a7ab-b821-4d1d-bb81-7bda28c651be	\N	PKWT
e0a0498a-2e06-4dca-832b-c6db2a9e1148	22	Muhammad Yaser Alfian	Alvi	22	85129735201		LAKI_LAKI	ISLAM	Jalan Gapuro 18/04, Pandanlandung, Wagir, Malang		Malang	2007-08-06	2026-09-21		t	7a02ad93-1a6b-4349-97d8-2c9e5c4a0972	\N	PKWT
e0a138c8-7543-4213-bfea-2ffd8205c1dd	23	Sandi Kurniawan	Sendi	23	83846951689		LAKI_LAKI	ISLAM	Besuki Wringinanom Poncokusumo	Crew Led	Malang	2004-04-22	2024-10-07	-	t	799aed62-f698-4ca5-9f2e-4c393275cc26	\N	PKWT
a54844c5-3a2c-4b58-8efa-fe264769bea1	24	Muhammad Pramono	Pram	24	81217062787		LAKI_LAKI	ISLAM	Jl Suropati singosari	Crew Led	Malang	2006-09-03	2024-11-01	-	t	98231609-79ae-44f6-a19f-617801443438	\N	PKWT
369f346b-f87a-4c45-900b-3917bd9d8a3d	25	Imlah	Imlah	25	82142705630		LAKI_LAKI	ISLAM	Jl Candi kalasan IV No 39B Malang	Crew Led	Situbondo	1996-03-07	2024-01-18	-	t	85fe04f3-309c-4502-8032-1ba9d54abb2c	\N	PKWT
77623b00-b355-471d-a9bd-dc8cabf614ce	26	Aldo Alamsyah	Aldo	26	82132096551		LAKI_LAKI	ISLAM	Jl Gunung Jati Pandanlandung Wagir Malang	Crew Led	Malang	2001-07-26	2024-08-11	BCA  3310971692 A/n ALDO ALAMSYAH	t	7864f3ac-dc94-416c-8609-e00dfec23a25	\N	PKWT
b1babf25-af98-4ac9-b7c9-238d99f88591	27	Tedy Ardi Yansa	Tedy	27	85749332837		LAKI_LAKI	ISLAM	Dsn Druju Rt 33 Rw 8 Tlogorejo,Pagak Kab Malang	Crew Led	Malang	2002-10-01	2024-12-01		t	e7f3f43c-8560-42c9-9817-1b8967734a53	\N	PKWT
370a02e1-a2cf-4663-a95b-677a05112ad0	28	Ahmad Jundillah	Jundi	28	85860004546		LAKI_LAKI	ISLAM	Bulupayung,Krebet Bululawang	Crew Led	Malang	2001-10-31	2024-04-20	-	t	dc75610d-dd54-494b-8011-1c702593afac	\N	PKWT
e3a4d92b-a5be-45e3-a418-07b0fdafa5c2	29	Visal Else	Visal	29	82257373088		LAKI_LAKI	ISLAM	Sumberawan,Toyomarto Singosari Kab Malang	Pic Led	Malang	2005-07-31	2024-03-01	BCA 3680510295  A/n Visal Else	t	247acbcc-3d48-47b6-877d-d37f44ebf8cb	\N	PKWT
069ca6b8-fbfc-4875-911f-44e213f61117	30	Galang Mas Suinendra Pradana	Galang	30	88989985890	82332347945	LAKI_LAKI	ISLAM	Dusun Plosokerep, 06/07, Dengkol, Singosari, Malang	Gudang Inventory	Trenggalek	2002-12-21	2026-03-01		t	44886b3f-678e-48cc-a3af-dfe9827ee5a2	\N	PKWT
034dfbde-432c-4509-ac37-30920890f4db	31	Ferryal Effendi Pratama	Effendi	31	81231919974	85103834044	LAKI_LAKI	ISLAM	Jalan Raya Bugis No. 6 05/04, Pakis, Kab. Malang	Service	Malang	2005-08-28	2026-09-21		t	1d4f2713-0e41-4ac0-b47a-bf41132c9a2b	\N	PKWT
4ea55a8c-66a4-4dc8-922d-7cc1a06fb52c	32	Muhammad Azharuddin	Azhar	32	895392159964	85718988024	LAKI_LAKI	ISLAM	Kewangen 03/02 Karangsari, Kebumen	Service	Kebumen	2001-10-19	2026-09-21		t	745c6581-f30f-4e04-b65d-0fa1a508d2b1	\N	PKWT
dcef7a29-e39c-436f-b277-08f52006d573	36	Muhamad Iqbal Shaldi Fauzil Adzim	Iqbal	36	89685350640	895402693783	LAKI_LAKI	ISLAM	Jl. Kertorejo No. 15A Ketawanggede, Lowokwaru, Malang	Human Resource Developement	Kediri	2004-02-21	2026-06-29	901816621688 seabank a/n muhamad iqbal shaldi	t	004649fc-e4c1-41f9-a5e2-73554219984b	\N	PKWT
82fcf9ba-7c14-4644-b457-123b978dddc5	37	Kanda Salsa Fatkhurrahman	Kanda	37	82232316233	85334539090	LAKI_LAKI	ISLAM	Jl. Sumbersari II/136 Lowokwaru, Malang	Human Resource Developement	Malang	2000-01-21	2026-06-30	Kanda Salsa Fatkhurrahman Sea bank : 901877954770	t	53a13204-e5cd-4346-b6b3-1a72a7b6d2b7	\N	PKWT
a9d76279-4ef8-4474-9aab-617064ab689f	38	Yesika Rahelya Simamora	Cika	38	81347385116	082166779722 (ibu)	PEREMPUAN	KATHOLIK	Jl. Istana Bandara 7, Singosari	Finance	Siborongborong	2006-09-23	2026-08-18	BRI : 109501006549531 // Yesika Seabank : 901602204203 // Yesika	t	f2099cc8-37da-488e-b8a6-e79bb8e12ac1	\N	PKWT
1d94258b-f050-4240-92de-74e22cb81194	1	Muhammad Burhanuddin	Burhan	1	81333445597	83834591998	LAKI_LAKI	ISLAM	Malang	Chief Executive Officer	Pasuruan	1998-05-14	2016-04-23	BCA  4390560686 A/n Muhammad Burhanuddin / BCA 3660399282 a.n Balqist Hamada	t	14d4cad5-189e-4b06-b121-72c148cc0751	\N	PKWT
6d567745-3288-43b6-b6cf-c3d18aaabaa7	3	Sahid Effendi	Sahid	3	81233339834	89516591559	LAKI_LAKI	ISLAM	Dsn. Panggung Sari Kab.Malang	Marketing	Malang	1997-06-11	2022-06-08	BNI 0754064148 A/n Uswatun hasanah	t	02c94227-b66b-4ecb-a643-0c0a21c8bd6c	\N	PKWT
51146e06-90ea-42ad-a91f-bf71cc1e3215	5	Muhammad Irfani Aziz	Irfani	5	85746642358	85646415183	LAKI_LAKI	ISLAM	Jl raya pagelaran Kab.Malang	K.Div Visual Production	Malang	1997-11-22	2023-06-13	BCA 0113335031 A/n M Irfani Aziz	t	7e583f6c-1c82-4425-b357-a9cd22d4ef00	\N	PKWT
d58b348b-992d-42e5-a1ad-c80887eaddcf	34	Hans Adiyatma Putra Aufa	Hans	34	81230267897	81359410575	LAKI_LAKI	ISLAM	Ngronggi, 03/01 Grudo, Kec. Ngawi, Ngawi	Sistem Informasi	Ngawi	2003-12-14	2026-06-07	Mandiri 1710016803507 a.n Hans Adiyatma Putra	t	694d2fe2-591c-4ae0-8bed-8b7761ddb8d8	\N	PKWT
8b6e4110-d40d-422a-80f3-baa9349515c1	35	Avicena Hawkins Mutahari	Avi	35	8988765928	82143180482	LAKI_LAKI	ISLAM	Jl. Setia 1 Gg. Nurul Huda, 05/12 Jatiwaringin, Pondok Gede, Bekasi	Service	Malang	2004-12-03	2026-06-22	0382004380 a.n BCA Avicenna Hawkins Mutahari	t	aed9f0cc-755c-4a69-9e65-328f842a2ec7	\N	PKWT
1b5de890-3254-4b8d-80f4-ab561b4bb2b1	2	Rohman Dwi Yahya	Rohman	2	81907007990/083129728444	85746011508//085855149732//085607401119//085895354179	LAKI_LAKI	ISLAM	Jl. Permadi Polehan RT/RW 11/04 Polehan  Malang	Manager	Malang	1997-12-23	2018-12-22	BCA 0190841731 A/n Rohman Dwi Yahya	t	f0ce7c83-d36a-404c-b193-76067e36d11d	\N	PKWT
50eec54e-46dd-4edd-9c65-2caa4aa132e6	4	Dhany Fatakhul Ghafara	Dhany	4	83834046926	81333253261	LAKI_LAKI	ISLAM	Jl. gapura pandanlandung rt18 rw04 Malang	K.div Sarana Prasarana	Malang	1999-05-24	2023-01-16	DANA 083834046926 A/n Dhany Fatakhul G.	t	8dca6df1-c978-4542-851a-a154d80d37a4	\N	PKWT
fc554bdc-305a-4944-bb54-2821d886793f	33	Muhammad Khunta Wijaya Danu	Khunta	33	85785802850		LAKI_LAKI	ISLAM	Jalan Bandara Palmerah XVI/P1 B, Cemorokandang, Kec. Kedungkandang	Service	Malang	2006-04-01	2026-02-12		t	4ee8d821-bfd1-44dd-a03f-c4d2fb1cf433	\N	PKWT
\.


--
-- TOC entry 5165 (class 0 OID 17283)
-- Dependencies: 239
-- Data for Name: leave_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.leave_request (id, leave_type, start_date, end_date, reason, attachment, status, reviewed_at, created_at, approved_by_id, employee_id, signed_attachment) FROM stdin;
7335bcde-f140-4434-bc88-90ed7c5189df	IZIN	2026-09-24	2026-09-23	anu testing coy		APPROVED	2026-09-21 14:56:17.940511+07	2026-09-21 14:53:08.113969+07	d7461acb-897c-4cf3-a40c-d3cc40c7b64d	d58b348b-992d-42e5-a1ad-c80887eaddcf	\N
962ca061-ed68-4c85-9969-ba9dda6edb35	IZIN	2026-09-24	2026-09-23	dadawasdas		APPROVED	2026-09-22 08:54:59.544014+07	2026-09-22 08:54:38.285268+07	d7461acb-897c-4cf3-a40c-d3cc40c7b64d	d58b348b-992d-42e5-a1ad-c80887eaddcf	\N
3945116d-428d-4ad7-b346-dbef526e5444	SAKIT	2026-09-23	2026-09-24	dawda	leave_attachments/_3c458cee-b6eb-4e01-9f53-c22a750d165b.jpeg	APPROVED	2026-09-22 09:06:21.976392+07	2026-09-22 09:04:49.204008+07	d7461acb-897c-4cf3-a40c-d3cc40c7b64d	d58b348b-992d-42e5-a1ad-c80887eaddcf	leave_attachments/signed/_3c458cee-b6eb-4e01-9f53-c22a750d165b.jpeg
e8631d2a-ecf7-4183-8c6e-049f8ac4d6ca	IZIN	2026-09-24	2026-09-26	dsg		REJECTED	2026-09-22 15:10:48.989121+07	2026-09-22 13:59:56.114779+07	d7461acb-897c-4cf3-a40c-d3cc40c7b64d	d58b348b-992d-42e5-a1ad-c80887eaddcf	
\.


--
-- TOC entry 5173 (class 0 OID 0)
-- Dependencies: 230
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- TOC entry 5174 (class 0 OID 0)
-- Dependencies: 232
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5175 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5176 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5177 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- TOC entry 5178 (class 0 OID 0)
-- Dependencies: 240
-- Name: daily_report_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.daily_report_log_id_seq', 5, true);


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 234
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5180 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- TOC entry 5181 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- TOC entry 4946 (class 2606 OID 17159)
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 17171)
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4940 (class 2606 OID 17148)
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4951 (class 2606 OID 17185)
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4954 (class 2606 OID 17168)
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4943 (class 2606 OID 17150)
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- TOC entry 4976 (class 2606 OID 17276)
-- Name: attendance_log attendance_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_log
    ADD CONSTRAINT attendance_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 17129)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4935 (class 2606 OID 17114)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4938 (class 2606 OID 17103)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4932 (class 2606 OID 17092)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4925 (class 2606 OID 17105)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4927 (class 2606 OID 17084)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4983 (class 2606 OID 17324)
-- Name: daily_report_log daily_report_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_report_log
    ADD CONSTRAINT daily_report_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 17212)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 17074)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4922 (class 2606 OID 17072)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 17062)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4972 (class 2606 OID 17262)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4962 (class 2606 OID 17243)
-- Name: employees_employee employees_employee_hikvision_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_hikvision_id_key UNIQUE (hikvision_id);


--
-- TOC entry 4965 (class 2606 OID 17241)
-- Name: employees_employee employees_employee_nik_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_nik_key UNIQUE (nik);


--
-- TOC entry 4967 (class 2606 OID 17239)
-- Name: employees_employee employees_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_pkey PRIMARY KEY (id);


--
-- TOC entry 4969 (class 2606 OID 17245)
-- Name: employees_employee employees_employee_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_user_id_key UNIQUE (user_id);


--
-- TOC entry 4980 (class 2606 OID 17297)
-- Name: leave_request leave_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 1259 OID 17183)
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- TOC entry 4947 (class 1259 OID 17182)
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- TOC entry 4952 (class 1259 OID 17197)
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4955 (class 1259 OID 17196)
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- TOC entry 4941 (class 1259 OID 17169)
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4974 (class 1259 OID 17282)
-- Name: attendance_log_employee_id_f3bfe1ae; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX attendance_log_employee_id_f3bfe1ae ON public.attendance_log USING btree (employee_id);


--
-- TOC entry 4928 (class 1259 OID 17130)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4933 (class 1259 OID 17125)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4936 (class 1259 OID 17126)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4923 (class 1259 OID 17111)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4981 (class 1259 OID 17330)
-- Name: daily_report_log_employee_id_734b05d1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX daily_report_log_employee_id_734b05d1 ON public.daily_report_log USING btree (employee_id);


--
-- TOC entry 4956 (class 1259 OID 17223)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4959 (class 1259 OID 17224)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4970 (class 1259 OID 17264)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4973 (class 1259 OID 17263)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4960 (class 1259 OID 17252)
-- Name: employees_employee_hikvision_id_991c01b4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employees_employee_hikvision_id_991c01b4_like ON public.employees_employee USING btree (hikvision_id varchar_pattern_ops);


--
-- TOC entry 4963 (class 1259 OID 17251)
-- Name: employees_employee_nik_c8c5874b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employees_employee_nik_c8c5874b_like ON public.employees_employee USING btree (nik varchar_pattern_ops);


--
-- TOC entry 4977 (class 1259 OID 17308)
-- Name: leave_request_approved_by_id_88cf7a1a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX leave_request_approved_by_id_88cf7a1a ON public.leave_request USING btree (approved_by_id);


--
-- TOC entry 4978 (class 1259 OID 17309)
-- Name: leave_request_employee_id_0dd5db52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX leave_request_employee_id_0dd5db52 ON public.leave_request USING btree (employee_id);


--
-- TOC entry 4987 (class 2606 OID 17177)
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4988 (class 2606 OID 17172)
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4989 (class 2606 OID 17191)
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4990 (class 2606 OID 17186)
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4994 (class 2606 OID 17277)
-- Name: attendance_log attendance_log_employee_id_f3bfe1ae_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attendance_log
    ADD CONSTRAINT attendance_log_employee_id_f3bfe1ae_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4985 (class 2606 OID 17120)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4986 (class 2606 OID 17115)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4984 (class 2606 OID 17106)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4997 (class 2606 OID 17325)
-- Name: daily_report_log daily_report_log_employee_id_734b05d1_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_report_log
    ADD CONSTRAINT daily_report_log_employee_id_734b05d1_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4991 (class 2606 OID 17213)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4992 (class 2606 OID 17218)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4993 (class 2606 OID 17246)
-- Name: employees_employee employees_employee_user_id_27bed289_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_user_id_27bed289_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4995 (class 2606 OID 17298)
-- Name: leave_request leave_request_approved_by_id_88cf7a1a_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_approved_by_id_88cf7a1a_fk_accounts_user_id FOREIGN KEY (approved_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4996 (class 2606 OID 17303)
-- Name: leave_request leave_request_employee_id_0dd5db52_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_employee_id_0dd5db52_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-09-24 13:23:23

--
-- PostgreSQL database dump complete
--

\unrestrict k4mCDOpQvnyst9ThENgcHhD2zJOhKbIm6Sxi5Pl43A4OMHI9flQPfSohUrk7tJl

