# Generated by Django 5.1.4 on 2026-09-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('PKWT', 'PKWT (Perjanjian Kerja Waktu Tertentu)')], default='PKWT', max_length=10, verbose_name='Jenis Kontrak')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='contracts/documents/%Y/', verbose_name='Dokumen Kontrak (PDF)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Kontrak',
                'verbose_name_plural': 'Kontrak',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HRNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CONTRACT_EXPIRY', 'Kontrak Hampir Habis'), ('BIRTHDAY', 'Ulang Tahun Karyawan')], max_length=20, verbose_name='Tipe Notifikasi')),
                ('message', models.TextField(verbose_name='Pesan Notifikasi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_notifications', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Notifikasi HR',
                'verbose_name_plural': 'Notifikasi HR',
                'ordering': ['-created_at'],
            },
        ),
    ]
