# Generated by Django 6.0.8 on 2026-09-26 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('IZIN', 'Izin'), ('CUTI', 'Cuti'), ('SAKIT', 'Sakit')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('signed_attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/signed/')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('AUTO_REJECTED', 'Ditolak Sistem')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'db_table': 'leave_request',
            },
        ),
    ]
