# Generated by Django 5.1.4 on 2026-09-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('IZIN', 'Izin'), ('CUTI', 'Cuti')], max_length=10, verbose_name='Jenis')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('reason', models.TextField(verbose_name='Alasan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('AUTO_REJECTED', 'Ditolak Otomatis (H-1)')], default='PENDING', max_length=15, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Review')),
                ('review_note', models.CharField(blank=True, default='', max_length=255, verbose_name='Catatan Review (opsional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Karyawan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='employees.employee', verbose_name='Direview oleh')),
            ],
            options={
                'verbose_name': 'Pengajuan Izin/Cuti',
                'verbose_name_plural': 'Pengajuan Izin/Cuti',
                'ordering': ['-created_at'],
            },
        ),
    ]
