# Generated by Django 6.1.1 on 2026-09-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='signed_attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/signed/'),
        ),
    ]
