# Generated by Django 5.1.4 on 2026-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='late_until',
            field=models.TimeField(blank=True, help_text='Khusus IZIN_TERLAMBAT: izin terlambat berlaku sampai jam ini', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CUTI', 'Cuti Tahunan'), ('IZIN', 'Izin Keperluan'), ('SAKIT', 'Sakit'), ('IZIN_TERLAMBAT', 'Izin Terlambat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20),
        ),
    ]
