# Generated by Django 5.1.4 on 2026-09-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikvisionRawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial', models.CharField(default='default', max_length=100)),
                ('serial_no', models.BigIntegerField()),
                ('event_time', models.DateTimeField()),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('employee_no', models.CharField(blank=True, default='', max_length=50)),
                ('name_on_device', models.CharField(blank=True, default='', max_length=255)),
                ('card_no', models.CharField(blank=True, default='', max_length=100)),
                ('card_type', models.CharField(blank=True, default='', max_length=50)),
                ('card_reader_no', models.IntegerField(blank=True, null=True)),
                ('door_no', models.IntegerField(blank=True, null=True)),
                ('verify_mode', models.CharField(blank=True, default='', max_length=100)),
                ('attendance_status', models.CharField(blank=True, default='', max_length=50)),
                ('attendance_label', models.CharField(blank=True, default='', max_length=100)),
                ('user_type', models.CharField(blank=True, default='', max_length=50)),
                ('raw_payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hikvision_raw_event',
                'ordering': ['-event_time'],
                'unique_together': {('device_serial', 'serial_no')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('event_time', models.DateTimeField()),
                ('attendance_type', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=10)),
                ('verification_mode', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(default='hikvision', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
                ('raw_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_record', to='attendance.hikvisionrawevent')),
            ],
            options={
                'db_table': 'attendance_log',
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_3d66ca_idx'), models.Index(fields=['attendance_date'], name='attendance__attenda_03b391_idx')],
            },
        ),
    ]
