# Generated by Django 6.0.8 on 2026-09-26 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikvisionRawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.BigIntegerField(verbose_name='Serial Event Mesin')),
                ('event_date', models.DateField(verbose_name='Tanggal Event')),
                ('event_time_raw', models.CharField(max_length=50, verbose_name='Waktu Event (Raw)')),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('employee_no', models.CharField(blank=True, max_length=50, verbose_name='ID Karyawan di Mesin')),
                ('card_no', models.CharField(blank=True, max_length=50, verbose_name='Nomor Kartu')),
                ('name_on_device', models.CharField(blank=True, max_length=255, verbose_name='Nama di Mesin')),
                ('verify_mode', models.CharField(blank=True, max_length=100, verbose_name='Mode Verifikasi')),
                ('door_no', models.IntegerField(blank=True, null=True, verbose_name='Nomor Pintu')),
                ('raw_payload', models.JSONField(verbose_name='Payload Lengkap (JSON)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Fetch')),
            ],
            options={
                'verbose_name': 'Hikvision Raw Event',
                'verbose_name_plural': 'Hikvision Raw Events',
                'db_table': 'hikvision_raw_event',
                'ordering': ['event_date', 'event_time_raw'],
                'unique_together': {('serial_no', 'event_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Tanggal Absen')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('HIKVISION_MACHINE', 'Mesin Hikvision'), ('WEB_LED_MODE', 'Web - Mode LED'), ('WEB_RENTAL', 'Web - Rental'), ('MANUAL_BY_HR', 'Manual HR')], default='HIKVISION_MACHINE', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('is_late', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_duration', models.DurationField(blank=True, null=True)),
                ('kpi_score', models.IntegerField(blank=True, null=True, verbose_name='Poin KPI')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_log',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
