# Generated by Django 6.1.1 on 2026-09-21 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Tanggal Absen')),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('HIKVISION_MACHINE', 'Mesin Hikvision'), ('WEB_LED_MODE', 'Web - Mode LED'), ('WEB_RENTAL', 'Web - Rental'), ('MANUAL_BY_HR', 'Manual HR')], default='HIKVISION_MACHINE', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('is_late', models.BooleanField(default=False)),
                ('is_overtime', models.BooleanField(default=False)),
                ('overtime_duration', models.DurationField(blank=True, null=True)),
                ('kpi_score', models.IntegerField(blank=True, null=True, verbose_name='Poin KPI')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'attendance_log',
            },
        ),
    ]
