# Generated by Django 5.1.4 on 2026-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='is_late_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
