# Generated by Django 5.1.4 on 2026-09-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('content', models.TextField(help_text='Laporan aktivitas harian (textarea).', verbose_name='Isi Laporan')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_log', models.OneToOneField(blank=True, help_text='Otomatis terhubung ke log absensi hari yang sama.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_report', to='attendance.attendancelog', verbose_name='Log Absensi Terkait')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Laporan Harian',
                'verbose_name_plural': 'Laporan Harian',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
