# Generated by Django 6.1.1 on 2026-09-22 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity', models.TextField(verbose_name='Aktivitas Pekerjaan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'daily_report_log',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
