# Generated by Django 6.0.8 on 2026-09-26 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('activity', models.TextField(verbose_name='Aktivitas Pekerjaan')),
                ('work_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kerja')),
                ('issue', models.TextField(blank=True, null=True, verbose_name='Kendala')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='employees.employee')),
            ],
            options={
                'db_table': 'daily_report_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
