# Generated by Django 6.1.1 on 2026-09-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='start_time',
        ),
    ]
