# Generated by Django 5.1.4 on 2026-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='daily_log_images/', verbose_name='Foto / Dokumentasi'),
        ),
    ]
