# Generated by Django 5.1.4 on 2026-10-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0002_dailylog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_log_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='daily_report.dailylog')),
            ],
        ),
    ]
