# Generated by Django 6.1.1 on 2026-09-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0002_alter_dailylog_options_remove_dailylog_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='issue',
            field=models.TextField(blank=True, null=True, verbose_name='Kendala'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='work_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link Kerja'),
        ),
    ]
