# Generated by Django 6.1.1 on 2026-09-22 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_report', '0003_dailylog_issue_dailylog_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
