# Generated by Django 5.1.4 on 2026-09-13 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('CV_LED', 'Kantor CV / Gudang LED'), ('RENTAL', 'Toko Rental'), ('CUSTOM', 'Lokasi Kustom')], default='CUSTOM', max_length=10, verbose_name='Tipe Lokasi')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('radius_meter', models.PositiveIntegerField(default=100, help_text='Batas toleransi jarak absen dalam meter.', verbose_name='Radius (meter)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lokasi Perusahaan',
                'verbose_name_plural': 'Lokasi Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('nik', models.CharField(help_text='Nomor Induk Karyawan (unik per karyawan)', max_length=20, unique=True, verbose_name='NIK')),
                ('role', models.CharField(choices=[('CV_KARYAWAN', 'Karyawan CV'), ('CV_INTERN', 'Intern CV'), ('CV_MAGANG', 'Magang CV'), ('LED_KARYAWAN', 'Karyawan LED'), ('LED_INTERN', 'Intern LED'), ('LED_MAGANG', 'Magang LED'), ('RENTAL_KARYAWAN', 'Karyawan Rental'), ('RENTAL_MAGANG', 'Magang Rental'), ('RENTAL_STAFF', 'Staff Rental'), ('CREW_GUDANG', 'Crew Gudang'), ('ADMIN_HR', 'Admin HR')], max_length=20, verbose_name='Role')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='Departemen')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Nomor HP')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Foto Profil')),
                ('is_active', models.BooleanField(default=True, help_text='Non-aktifkan untuk soft-delete karyawan.', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_employee', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['full_name'],
            },
        ),
    ]
