# Generated by Django 6.1.1 on 2026-09-21 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=50, unique=True, verbose_name='Nomor Karyawan (ID)')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nama Lengkap')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Panggilan')),
                ('hikvision_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Mesin Hikvision')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='No HP Pribadi (WA)')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='No HP Darurat')),
                ('gender', models.CharField(choices=[('LAKI_LAKI', 'Laki-laki'), ('PEREMPUAN', 'Perempuan')], max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(max_length=100, verbose_name='Jabatan / Role')),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('join_date', models.DateField(verbose_name='Tanggal Masuk Kerja')),
                ('bank_account_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Info Rekening Bank')),
                ('is_active', models.BooleanField(default=True, verbose_name='Karyawan Aktif')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_employee',
            },
        ),
    ]
