# Generated by Django 6.1.1 on 2026-09-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='No HP Darurat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='whatsapp_number',
            field=models.CharField(max_length=255, verbose_name='No HP Pribadi (WA)'),
        ),
    ]
