# Generated by Django 5.1.4 on 2026-10-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Foto Karyawan'),
        ),
    ]
