# Generated by Django 6.1.1 on 2026-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Berakhir Kontrak'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('PKWT', 'PKWT (Kontrak)'), ('PKWTT', 'PKWTT (Tetap)'), ('FREELANCE', 'Freelance'), ('INTERN', 'Magang')], default='PKWT', max_length=50, verbose_name='Jenis Kontrak'),
        ),
    ]
