# Generated by Django 5.1.4 on 2026-09-13 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(help_text='Tanggal hari libur yang dipindahkan.', verbose_name='Tanggal Libur Asli')),
                ('new_day_off_date', models.DateField(help_text='Tanggal pengganti hari libur.', verbose_name='Tanggal Libur Baru')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Alasan Perubahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_overrides', to='employees.employee', verbose_name='Dibuat oleh (Admin)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Override Hari Libur',
                'verbose_name_plural': 'Override Hari Libur',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_off_weekday', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=2, verbose_name='Hari Libur')),
                ('effective_date', models.DateField(help_text='Jadwal ini berlaku mulai tanggal ini ke depan.', verbose_name='Berlaku Mulai Tanggal')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employee', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Jadwal Kerja',
                'verbose_name_plural': 'Jadwal Kerja',
                'ordering': ['-effective_date'],
            },
        ),
    ]
